# -*- coding: utf-8 -*-
"""project138.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BWhUxQYubpVI5l8UtYKajXR9_3j1mcWS
"""

!pip install Kaggle

from google.colab import files 
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d tmdb/tmdb-movie-metadata

!ls

!unzip tmdb-movie-metadata.zip

!ls

import pandas as pd
df1=pd.read_csv('tmdb_5000_credits.csv')
df2=pd.read_csv('tmdb_5000_movies.csv')
df1.head()
#df2.head()

df1.columns=['id','title','cast','crew']
df2=df2.merge(df1,on ='id')